"""Strategy defaults, validation, and analyzer command-line options."""

import ssq_cli as _cli
import ssq_config_models as _config_models
import ssq_strategy_validation as _strategy_validation

POOL_SIZE_RED = _config_models.POOL_SIZE_RED
RED_HIGH_COUNT = _config_models.RED_HIGH_COUNT
RED_LOW_COUNT = _config_models.RED_LOW_COUNT
NUM_BLUE_BALLS = _config_models.NUM_BLUE_BALLS
REJECTION_LIB_SIZE = _config_models.REJECTION_LIB_SIZE
RANDOM_SEED = _config_models.RANDOM_SEED
REJECTION_SEED_MULTIPLIER = _config_models.REJECTION_SEED_MULTIPLIER
BACKTEST_PERIODS = _config_models.BACKTEST_PERIODS
INTERACTIVE_THRESHOLD = _config_models.INTERACTIVE_THRESHOLD
COUNTDOWN_SECONDS = _config_models.COUNTDOWN_SECONDS
NUM_RECOMMENDATIONS = _config_models.NUM_RECOMMENDATIONS
MAX_SHARED_RED_BALLS = _config_models.MAX_SHARED_RED_BALLS
RULE_AUDIT_PERIODS = _config_models.RULE_AUDIT_PERIODS
TOTAL_RED_COMBINATIONS = _config_models.TOTAL_RED_COMBINATIONS
RED_POOL_MODES = _config_models.RED_POOL_MODES

DEFAULT_PARAMS = _strategy_validation.DEFAULT_PARAMS
INTEGER_PARAM_NAMES = _strategy_validation.INTEGER_PARAM_NAMES
FLOAT_PARAM_NAMES = _strategy_validation.FLOAT_PARAM_NAMES
normalize_integer_param = _strategy_validation.normalize_integer_param
normalize_float_param = _strategy_validation.normalize_float_param
validate_weight_group = _strategy_validation.validate_weight_group
validate_param_ranges = _strategy_validation.validate_param_ranges
validate_strategy_params = _strategy_validation.validate_strategy_params


StrategyConfig = _config_models.StrategyConfig
DEFAULT_STRATEGY_CONFIG = _config_models.DEFAULT_STRATEGY_CONFIG
AnalyzerOptions = _config_models.AnalyzerOptions
LoadedStrategyParams = _config_models.LoadedStrategyParams


build_argument_parser = _cli.build_argument_parser
parse_cli_options = _cli.parse_cli_options
