"""Compatibility exports for bet parsing and prize calculations."""

import ssq_bet_parsing as _bet_parsing
import ssq_prize_calculation as _prize_calculation

SINGLE_HEADER_PATTERN = _bet_parsing.SINGLE_HEADER_PATTERN
DUPLEX_HEADER_PATTERN = _bet_parsing.DUPLEX_HEADER_PATTERN
SINGLE_BET_PATTERN = _bet_parsing.SINGLE_BET_PATTERN
parse_single_bet_line = _bet_parsing.parse_single_bet_line
parse_duplex_section = _bet_parsing.parse_duplex_section
validate_parsed_bets = _bet_parsing.validate_parsed_bets
parse_report_bets_content = _bet_parsing.parse_report_bets_content
parse_report_bets = _bet_parsing.parse_report_bets
calculate_single_prize = _prize_calculation.calculate_single_prize
calculate_duplex_prize = _prize_calculation.calculate_duplex_prize
