"""Pure text formatting for complete analysis reports."""

import ssq_backtest_reporting as _backtest_reporting
import ssq_recommendation_reporting as _recommendation_reporting
import ssq_report_builder as _report_builder
import ssq_report_models as _report_models
import ssq_rule_reporting as _rule_reporting

AnalysisReportData = _report_models.AnalysisReportData
PRIZE_DISPLAY_ORDER = _backtest_reporting.PRIZE_DISPLAY_ORDER
format_strategy_parameters = _backtest_reporting.format_strategy_parameters
format_backtest_metrics = _backtest_reporting.format_backtest_metrics
format_pool_comparison = _backtest_reporting.format_pool_comparison
format_window_stability = _backtest_reporting.format_window_stability
format_rank_band_distribution = _backtest_reporting.format_rank_band_distribution
format_prize_counts = _backtest_reporting.format_prize_counts
format_backtest_report = _backtest_reporting.format_backtest_report
format_audit_window = _rule_reporting.format_audit_window
format_rule_audit_report = _rule_reporting.format_rule_audit_report
format_recommendations_report = (
    _recommendation_reporting.format_recommendations_report
)
build_analysis_report = _report_builder.build_analysis_report
